### ISSUE TITLE
Standardized format for PSO / draw call capture

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-Ecosystem#2]
It would be desirable to create a standardized format for capturing PSO and draw call data from live applications. The intent is to enable tools to replay specific draw calls outside the app.

This would facilitate IHV bug reporting, plus enable the creation of repositories of real-world draw calls for regression testing and/or performance tracking.

**Comment by plohrmann** [comment]
Don't we essentially have that with vktrace, and the single frame capture functionality? Oh, it sounds like you want to cull that down even further to a single draw-call. Right?

**Comment by KarenGhavam-lunarG** [comment]
I am also wondering if this is functionality provided by RenderDoc (or would be easy to add it to RenderDoc). Without a thorough understanding of RenderDoc, it is not possible for me to say one way or the other. Perhaps @baldurk could evaluate it?

**Comment by baldurk** [comment]
You could have a renderdoc capture with only one drawcall so it's technically supported, but removing all but a single draw from a larger capture is not currently a feature and I guess that's really what you mean.

I think specifying how a single draw is stored probably won't be much less complex than specyfing how to store an entire frame capture, since a single draw could have a lot of dependencies, so you'd end up having to specify how store a lot of data. Apart from that I'm not sure you can ignore the other work in the draw's subpass (or other subpasses in that renderpass) and still necessarily have a repro case, or a fair performance test.

**Comment by plohrmann** [comment]
I had a similar concern about the complexity from other draws at first, but can't we already identify all the inputs to the draw call, and then just capture those buffer contents? Then we need to store them with enough meta data so that they can be reloaded and reconnected to where they need to be. We don't actually need to store any API calls, just the contents that feeds into the calls. A tool may want to just inspect all the inputs without actually replaying them, or it may want to regenerate API calls to replay the same workload. It may not be a exact mapping back to the original state of the draw call, but it will recreate a seemingly identical call.

**Comment by baldurk** [comment]
Right, I'm not sure what you mean about storing API calls, but that's what I was suggesting. You still have to be able to specify how to store any type of memory or image, including e.g MSAA images that can't be natively copied to a buffer, or images with sparse bindings. I'm also not sure you can remove any draw from its renderpass, particularly if it's using subpass inputs. My concern is that the amount of dependencies means you end up with something that's almost as expressive as a full frame capture, there's no simple 'just the draw' subset.

**Comment by HansKristian-Work** [comment]
I think there's a bit more to this problem than accurately capturing a draw call. Part of the use-cases I can think of is:

- It must be portable across devices, OSes and driver versions. I think this will be easier, because we don't necessarily need to consider accurately capturing the buffer/image layout in memory as the application sees it, but rather the contents, so memory type mismatch probably (famous last words) won't be a big deal. If an ISV gives me a problematic draw-call I would like to be able to run that over many different hardware configurations and driver versions to track down where regressions or similar started happening. Unfortunately, this is an aspect of Vulkan which is a bit annoying. Perhaps the device simulation layer can help, but I'd rather we find a way to make it portable by design for this case.

- Sometimes, the only interesting part is the shader itself, not running that shader. This could be for cases where we want to repro a shader compile going wrong, or just regression testing cycle counts. A good example here would be "here's a PSO without spirv-opt and here's one with and the difference in performance is dramatic." With a standard dump format, IHVs should be able to take that and convert it to ISA for relevant hardware configs.

- It would be interesting if we could drive shaders, especially fragment shaders, with "fake" input. If a fragment shader does not have side-effects, it would be nice if the format would facilitate running a shader with dummy input at any resolution, which could make it easier to A/B test performance.

- Capturing lone draw calls is always going to be a bit sketchy for performance comparisons, especially tilers I think. LOAD_OP_LOAD has some cost, and we cannot avoid loading attachments like that when replaying a single draw call and we want the output to be accurate. Input attachments also get kinda tricky, because I think we need to record the entire render pass structure to get an accurate reproduction of the shader. E.g. input attachments behave quite differently based on other subpasses.

- Should be possible to take these dumps and build an an-hoc regression test suite out of them. Needs some thinking what this actually means in practice ...

Afaik, there are three tools which could potentially do this job:
- RenderDoc
- vktrace
- Device simulation layer

If RenderDoc supported portable captures with a stable format (multiple independent implementations can consume and produce the format), perhaps this would be a solved problem? :P

**Comment by nsubtil** [comment]
From a wider discussion on this topic, we came out with the idea that there are really two problems worth solving which this issue seems to try to address:

### Allowing developers to capture, manipulate and play back API traces

To some extent this is done by existing tools (esp. RenderDoc), but there are underlying issues around portability across Vulkan implementations (memory types being a big deal here). There are also use cases where really old traces are routinely used, which would imply some sort of backwards compatibility for trace playback. We also don't have a strong ecosystem of tools to manipulate traces today, which limits the usefulness of captured traces.

There are several interesting use cases here, ranging from debugging to automated regression testing and performance tracking.

### Capturing Vulkan implementation bugs

One particular pain point right now is that CTS testing is not really very similar to real-world workloads. Many implementation problems end up being discovered by developers trying to build Vulkan apps. Due to the process and timelines involved in reporting implementation bugs and getting them fixed, it is fairly common for developers to simply work around any bugs they run into. And among the subset of bugs that get reported to IHVs, very few get turned into CTS tests in practice.

If we had a way to automatically capture a PSO/draw call on demand and play it back later, this would make it easier to build bug reporting functionality into debugging tools, creating a lower-friction path to getting bug reports into IHVs hands as well as more coverage in CTS. This would contribute to improving the quality of Vulkan as a whole.

These two problems don't necessarily share the same solution, but they seem to intercept. Not clear what the best course of action is just yet.

**Comment by nsubtil** [comment]
Nat Duca @ Google offered to look into whether we can get the Vulkan tools folks together for a face-to-face meeting, perhaps sometime in Q2. There seems to be enough interest within the community, and it would help shed some light on the right course of action for this issue (among other tools-related topics), but it's not yet clear how feasible it would be to host such a meeting.

In the meantime, it doesn't look like there are many resources available for this effort at the moment. Unless someone steps up and offers to put some time into this, we'll be tabling this issue for the next few months.

**Comment by HansKristian-Work** [comment]
I've been pondering on a more developer-centric library which intersects with this work.

There are many objects which are recommended to build ahead of time, such as: 
  - VkDescriptorSetLayout
  - VkPipelineLayout
  - VkRenderPass
  - VkPipeline

In at least my personal renderer, I cache/hash these objects based on the data provided. I assume this is roughly how most engines work due to the inherent difficulty in pre-computing all permutations of these statically for any non-trivial content.

I'm thinking of an approach which serializes this to disk and can be pulled in at load time to warm up the caches and avoids any last minute pipeline builds. This sounds like a fairly simple re-useable library to me, and could play nicely with PSO captures for reproduction purposes.

I believe @danginsburg also mentioned a use-case like this in one of the meetings.

**Comment by HansKristian-Work** [comment]
Update: I've been plugging on a library on the side which captures PSOs and replays them for internal engine use. I've got some plans to build a layer / replayer tool suite to be able to send shader related repro issues using this as well. https://github.com/Themaister/Fossilize

**Comment by HansKristian-Work** [comment]
Update, been trying to export Fossilize state from RenderDoc on the side: https://github.com/Themaister/RenderDoc/tree/fossilize.
I can export the static state now. Not enough to make a portable draw call, but it's a start.

**Comment by marty-johnson59** [comment]
This repository is being archived as it has been replaced with the vulkan.org website (https://www.vulkan.org) and is no longer being maintained (i.e., issues posted here are no longer being addressed ).  After reviewing issues posted here, most (if not all) have been resolved or have already been re-opened in Vulkan-Docs (https://github.com/KhronosGroup/Vulkan-Docs) or other repositories for further consideration.  Therefore, all issues in this repository will be closed.  If you believe your issue has not yet been resolved, please re-open in Vulkan-Docs.  Thanks!
