### ISSUE TITLE
Disposition of KhronosGroup/Vulkan-Samples Repository

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-Ecosystem#28]
The Vulkan-Samples [repository](https://github.com/KhronosGroup/Vulkan-Samples) appears to be inactive.  It was last updated nearly a year ago.  No one responded to a query about who was curating it.

Should this repository be added to the project map?

Who is the clear owner?

**Comment by HansKristian-Work** [comment]
Good question. I think the intention was to have a dumping ground for various samples, but it seems to have been lost to the sands of time.

**Comment by dgkoch** [comment]
I believe @mre4ce (Johannes (JP) van Waveren) was (at least for atw sample) but he passed away. I don't know if anyone else from Oculus is interested in taking that up? @gkennickell ?

**Comment by TomOlson** [comment]
>  No one responded 

Who am I, chopped liver? 

(I have always wanted to say that! :-) :-) :-))

It has two outstanding PRs. Was going to suggest that the Eco team discuss and that we resolve next week F2F.

**Comment by nsubtil** [comment]
We won't have a chance to discuss this beforehand. If we're interested in a F2F discussion, feel free to add it to the agenda --- eco group members can advise.

**Comment by karl-lunarg** [comment]
> Who am I, chopped liver?

Sorry, Tom!!  I probably meant to say that no one stepped up to be the owner or curator.

Discussed in today's meeting.

Some Possibilities:

1) (not desirable) Do nothing
2) (not desirable) Delete it
3) Archive the repo (GitHub's definition of an archive)
4) Archive and rename
5) Someone volunteers to host in another GitHub outside of KhronosGroup
6) Someone volunteers to rename and own/curate as a KhronosGroup repo
7) Someone volunteers to own/curate current repo

A primary concern is that no one appears to be curating the repository, which may result in bad user experiences.  A secondary concern is that the current contents don't represent a good set of samples.

The repository contents are:
1) atw sample
2) deviceinfo sample
3) GLSL compilation layer (Adds GLSL->SPIR-V conversion by hooking vkCreateShaderModule)
4) Vulkan queue multiplexer layer

The GitHub repository "archive" [process](https://help.github.com/articles/archiving-repositories/) does not save off the repo contents someplace and then remove the repo.  Instead, it marks the repo as archived and read-only, disabling the ability to create or modify issues and pull requests.  An archived repo can very easily be unarchived.

It is also easy to [rename](https://help.github.com/articles/renaming-a-repository/) a GitHub repository.

Archiving the repo is an attractive solution because it clearly sends the message that the repo is not maintained and is not accepting updates.  The [KhronosGroup/Vulkan-LoaderAndValidationLayers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) repo is a good example of an archived repo, in case you want to see what one looks like.  (Its contents were moved to other repos)

Renaming the repo is also desirable because it frees up the `Vulkan-Samples` name in case there's ever an effort to build a KhronosGroup samples repo.  It also removes the implication that the current repo contains a comprehensive set of samples.

Unless someone steps up to take over the repo (options 5, 6, 7), it is likely that the Ecosystem group will propose to the WG at the upcoming F2F to rename and archive the repo (option 4).  New name TBD.

**Comment by Cazadorro** [comment]
Isn't this similar to what you wanted to achieve? https://github.com/LunarG/VulkanSamples?  What was the purpose of https://github.com/KhronosGroup/Vulkan-Samples repository? I didn't even know that repository existed until this issue.  

I'm not sure it would make sense to hand it off to some one else when LunarG's repo appears to bear the mantle of "comprehensive vulkan sample repository" much more than Vulkan-Samples ever did.  I'd also be cautious of taking the "Get Volunteers to take care of it" because there *really* aren't that many people out there *right now* who know vulkan well enough to be confident they could maintain Khronos Vulkan repos with latest best practices, let alone be willing to take on the extra effort of volunteer upkeep. Take a look at who answers the questions on Stack Overflow about vulkan, there's only like 5 guys *maybe* that would be able to take that kind of mantel, and some of them already maintain [their own vulkan related repos](https://github.com/SaschaWillems/Vulkan).

**I think in this case, especially because of LunarG's repo, archiving is the best thing to do here**.   But I caution  Khronos group on taking this kind of slippery slope on all Khronos sponsored educational materials that have been neglected. I don't believe Vulkan yet has the outside expert base to afford too many purely voluntary efforts, especially on materials that may rely on updates to Khronos standards that initially only they themselves would be experts on.

**Comment by krOoze** [comment]
Is it naive of me to think that Khronos/authors have internlly some kind of snippet/example/demo of each released feature? Might be nice to be dumped there, even if not maintained long term.

**Comment by nsubtil** [comment]
As discussed before, we've now archived the repository. We'll leave the option of renaming open in the future should the need arise to repurpose the Vulkan-Samples repo name.

Closing.
